"""
ZenZap API client.

Supports both credential types documented at
https://docs.zenzap.co/api-reference/authentication

  - OAuth 2.0 client credentials  (RECOMMENDED - no per-request signing)
  - Static API key + HMAC-SHA256  (fallback if your bot was created this way)

The client auto-selects based on which env vars are present.

On Railway these come from the service's environment variables, not a .env
file — nothing here reads from disk for credentials.

Env vars
--------
ZENZAP_BASE_URL       e.g. https://api.zenzap.co

OAuth mode:
  ZENZAP_CLIENT_ID
  ZENZAP_CLIENT_SECRET

Static key mode:
  ZENZAP_API_KEY
  ZENZAP_API_SECRET
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import requests
import yaml

DEFAULT_BASE_URL = "https://api.zenzap.co"

# Minimum scopes this codebase needs. Narrower = smaller blast radius if leaked.
DEFAULT_SCOPES = (
    "channel:list channel:read message:send task:write member:read"
)


class ZenZapError(RuntimeError):
    """Raised when the ZenZap API returns a non-success response, or is
    unreachable. Network failures are wrapped in this so a single site's
    send can fail without taking the whole run down with it."""


def _env(name: str) -> Optional[str]:
    """Read an env var, stripped of surrounding whitespace.

    Also trims a trailing slash from URLs so base_url + path can't produce a
    double slash.
    """
    value = os.environ.get(name)
    if value is None:
        return None
    value = value.strip()
    return value.rstrip("/") if value.startswith("http") else value


_LOCKFILE = Path(__file__).resolve().parent / "config" / "topic_ids.yaml"
_lockfile_cache: Optional[dict] = None


def _load_topic_lockfile(path: Path = _LOCKFILE) -> dict:
    """name -> topic UUID, generated by jobs/resolve_topics.py."""
    global _lockfile_cache
    if _lockfile_cache is not None:
        return _lockfile_cache
    if not path.exists():
        raise ZenZapError(
            f"Missing {path.name}. Run `python jobs/resolve_topics.py` first — "
            f"it maps your ZenZap group names to topic IDs."
        )
    data = yaml.safe_load(path.read_text()) or {}
    _lockfile_cache = data.get("topics") or {}
    return _lockfile_cache


@dataclass
class ZenZapClient:
    # _env() strips whitespace. Pasting a value into a hosting panel very often
    # brings a trailing newline with it, and every symptom is baffling:
    #   base_url  -> DNS lookup for "api.zenzap.co%0a", "Name or service not known"
    #   api_secret-> HMAC computed over the wrong bytes, silent 401
    #   api_key   -> 401 with a key that looks correct on screen
    # Cheaper to strip than to diagnose. ingest/db.py does the same for
    # DATABASE_URL, for the same reason.
    base_url: str = field(default_factory=lambda: _env("ZENZAP_BASE_URL") or DEFAULT_BASE_URL)
    client_id: Optional[str] = field(default_factory=lambda: _env("ZENZAP_CLIENT_ID"))
    client_secret: Optional[str] = field(default_factory=lambda: _env("ZENZAP_CLIENT_SECRET"))
    api_key: Optional[str] = field(default_factory=lambda: _env("ZENZAP_API_KEY"))
    api_secret: Optional[str] = field(default_factory=lambda: _env("ZENZAP_API_SECRET"))
    scopes: str = DEFAULT_SCOPES
    timeout: int = 20

    _token: Optional[str] = field(default=None, repr=False, init=False)
    _token_expires_at: float = field(default=0.0, repr=False, init=False)
    _topic_cache: dict = field(default_factory=dict, repr=False, init=False)

    # ------------------------------------------------------------------ auth

    @property
    def mode(self) -> str:
        if self.client_id and self.client_secret:
            return "oauth"
        if self.api_key and self.api_secret:
            return "hmac"
        raise ZenZapError(
            "No ZenZap credentials found. Set ZENZAP_CLIENT_ID + ZENZAP_CLIENT_SECRET "
            "(OAuth, preferred) or ZENZAP_API_KEY + ZENZAP_API_SECRET (static key)."
        )

    def _access_token(self) -> str:
        """Mint / reuse an OAuth bearer token. Cached until 60s before expiry."""
        now = time.time()
        if self._token and now < self._token_expires_at - 60:
            return self._token

        resp = requests.post(
            f"{self.base_url}/oauth/token",
            data={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
                "scope": self.scopes,
            },
            timeout=self.timeout,
        )
        if resp.status_code != 200:
            raise ZenZapError(f"OAuth token request failed [{resp.status_code}]: {resp.text}")

        payload = resp.json()
        self._token = payload["access_token"]
        self._token_expires_at = now + int(payload.get("expires_in", 3600))
        return self._token

    @staticmethod
    def sign(secret: str, timestamp: int, payload: str) -> str:
        """HMAC-SHA256 of '{timestamp}.{payload}', hex encoded.

        payload is the raw JSON body for POST/PUT/PATCH/DELETE,
        or the full URI (path + query string) for GET.
        """
        message = f"{timestamp}.{payload}"
        return hmac.new(secret.encode(), message.encode(), hashlib.sha256).hexdigest()

    # --------------------------------------------------------------- request

    def _request(self, method: str, path: str, body: Optional[dict] = None) -> Any:
        url = f"{self.base_url}{path}"
        headers = {}
        data = None

        if body is not None:
            # Compact separators matter: the signature is over these exact bytes.
            data = json.dumps(body, separators=(",", ":"))
            headers["Content-Type"] = "application/json"

        if self.mode == "oauth":
            headers["Authorization"] = f"Bearer {self._access_token()}"
        else:
            ts = int(time.time() * 1000)
            signed_payload = data if method != "GET" else path
            headers["Authorization"] = f"Bearer {self.api_key}"
            headers["X-Signature"] = self.sign(self.api_secret, ts, signed_payload or "")
            headers["X-Timestamp"] = str(ts)

        try:
            resp = requests.request(method, url, headers=headers, data=data,
                                    timeout=self.timeout)
        except requests.exceptions.RequestException as exc:
            # DNS failure, timeout, connection reset. Previously this escaped as
            # a raw requests exception and aborted the entire run on the first
            # site, so a blip mid-loop meant sites 2-5 silently got nothing.
            raise ZenZapError(f"{method} {path} unreachable: {exc}") from exc

        if resp.status_code >= 400:
            raise ZenZapError(f"{method} {path} failed [{resp.status_code}]: {resp.text}")

        if not resp.content:
            return None
        try:
            return resp.json()
        except ValueError:
            return resp.text

    # ----------------------------------------------------------------- verbs

    def list_topics(self, limit: int = 100) -> list[dict]:
        """All topics the bot is a member of, following pagination."""
        topics, cursor = [], None
        while True:
            path = f"/v2/topics?limit={limit}"
            if cursor:
                path += f"&cursor={cursor}"
            page = self._request("GET", path)
            topics.extend(page.get("topics", []))
            if not page.get("hasMore"):
                break
            cursor = page.get("nextCursor")
            if not cursor:
                break
        return topics

    def topic_id_for(self, name: str) -> str:
        """Resolve a ZenZap group NAME to its topic UUID via the lockfile.

        Why not externalId: ZenZap only accepts externalId at topic creation
        (TopicPatchRequest takes name and description only). Your groups already
        exist, so names are the only handle available.

        Why a lockfile rather than a live name lookup: if someone renames a
        group in the app, a live lookup would either fail or — worse — match a
        different group and reroute alerts to the wrong site's staff. Pinning
        UUIDs means a rename causes a loud, obvious failure instead.

        Regenerate with: python jobs/resolve_topics.py
        """
        if name in self._topic_cache:
            return self._topic_cache[name]

        lock = _load_topic_lockfile()
        key = name.strip().casefold()
        for locked_name, topic_id in lock.items():
            if locked_name.strip().casefold() == key:
                self._topic_cache[name] = topic_id
                return topic_id

        raise ZenZapError(
            f"ZenZap group {name!r} is not in config/topic_ids.yaml. "
            f"Run `python jobs/resolve_topics.py` — and check TAPPY is a member "
            f"of that group, since the API hides topics the bot isn't in."
        )

    def send_message(
        self,
        text: str,
        *,
        topic_id: Optional[str] = None,
        topic_name: Optional[str] = None,
        external_id: Optional[str] = None,
    ) -> dict:
        """Send a text message to a topic.

        Pass either topic_id (UUID) or topic_name (the ZenZap group name).

        external_id is your own idempotency/tracking handle for the message —
        set it to something deterministic (e.g. 'nory-2026-08-19-solihull')
        so you can tell whether a job already posted today.
        """
        if not topic_id:
            if not topic_name:
                raise ValueError("Provide topic_id or topic_name")
            topic_id = self.topic_id_for(topic_name)

        if len(text) > 10_000:
            text = text[:9_990] + "\n… (truncated)"

        body = {"topicId": topic_id, "text": text}
        if external_id:
            body["externalId"] = external_id[:61]  # API caps externalId at 61 chars
        return self._request("POST", "/v2/messages", body)

    def create_task(
        self,
        title: str,
        *,
        topic_id: Optional[str] = None,
        topic_name: Optional[str] = None,
        assignees: Optional[list[str]] = None,
        due_at: Optional[int] = None,
        description: Optional[str] = None,
    ) -> dict:
        """Create a ZenZap task in a topic.

        Use this instead of a plain message when you want an answer back.
        A message is noise; a task assigned to the GM with a due date is
        accountability, and you can query completion later via GET /v2/tasks.
        """
        if not topic_id:
            if not topic_name:
                raise ValueError("Provide topic_id or topic_name")
            topic_id = self.topic_id_for(topic_name)

        body: dict[str, Any] = {"topicId": topic_id, "title": title}
        if assignees:
            body["assignees"] = assignees
        if due_at:
            body["dueAt"] = due_at
        if description:
            body["description"] = description
        return self._request("POST", "/v2/tasks", body)

    def members(self) -> list[dict]:
        """All active org members. Use to map names -> profileIds for @mentions."""
        return self._request("GET", "/v2/members?limit=100").get("members", [])

    def org_units(self) -> list[dict]:
        """Org units are ZenZap's 'teams / locations' — likely already your 6 sites."""
        return self._request("GET", "/v2/org-units?limit=100").get("orgUnits", [])


def mention(profile_id: str) -> str:
    """Format an @mention. The profile must be a member of the target topic."""
    return f"<@{profile_id}>"
